### ISSUE TITLE
Line 273 problem

### ISSUE THREAD

**Issue by xiekunwhy** [dblhlx/PySNPIndex#1]
Hi,
It always telling me problem's like following when I run python3 PyBSASeq_DSI.py.

  File "PyBSASeq_DSI.py", line 273
    i += 1
    ^
SyntaxError: invalid syntax

Best wishes,
Kun

**Comment by dblhlx** [comment]
Hi Kun,

Sorry for the late reply. I did not find this until today (11/27/2019), I am still learning how to use GitHub.

Thanks for reporting the bug. There was an additional "(" in line 272, which lead to the SyntaxError. Credit should go to Julien Frouin from France. Please let me know if this did not solve the problem.

Jianbo

**Comment by dblhlx** [comment]
This issue is fixed in the new version of the script.

**Comment by xiekunwhy** [comment]
Hi, Jianbo

New script works well. Thank you.

Kun
